// get all
GET http://localhost:3001/api/order
###
// find by id
GET http://localhost:3001/api/menu/66528b3b612b39bc526bc9d3 HTTP/1.1
###
DELETE http://localhost:3001/api/2
###
POST http://localhost:3001/api/order
// older unexpired token
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3R1c2VyIiwiaWQiOiI2NjUzNzdkNTIzMTljODI5NjFkMjIzOWIiLCJpYXQiOjE3MTY3Njg3Mjh9.0v0lYJJ4zb70jWE598npKScFfwF44z_INuMcUeJ3Ozs
    {
       
        "items":["6652a3679410615f08881889","6652a3679410615f0888188d", "6652a3679410615f0888188c"]
        
    }
###
// new expireable token 
Content-Type: application/json
Authorization: Bearer xxx
    {
       
        "items":["6652a3679410615f08881889","6652a3679410615f0888188d", "6652a3679410615f0888188c"]
        
    }
###
POST http://localhost:3001/api/user
Content-Type: application/json


    {
        "username": "testuser",
        "firstName": "Test",
        "lastName": "User",
        "password": "testpassword"
    }

###
POST http://localhost:3001/api/login
Content-Type: application/json

    {
        "username": "testuser",
        "password": "testpassword"
    }

###
POST http://localhost:3001/api/login
Content-Type: application/json

{
    "username":"goolnur",
    "password":"mango"
}
###
POST http://localhost:3001/api/user
Content-Type: application/json

{
    "username":"goolnur",
    "name":"Gul Noor",
    "password":"mango"
}
###
